import "~/styles/globals.css";

import { Inter, Montserrat } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { createClient } from "~/utils/supabase/server";
import { redirect } from "next/navigation";

const monsterrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

// export const metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const supabase = createClient();
  // const {
  //   data: { user },
  // } = await supabase.auth.getUser();
  // console.log(user, ">>>>>>>");
  // if (!user) {
  //   return redirect("/auth/login");
  // }
  return (
    <html lang="en">
      <body className={`${monsterrat.className}`}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
